baseURL = "http://blog.breakering.com"
languageCode = "zh-CN"
title = "Jacob个人技术博客"
theme = "maupassant"
googleAnalytics = "UA-130599767-1"  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "Jacob"

[params]
  author = "Jacob"
  subtitle = "Talk is cheap!Show me the code!"
  keywords = "Jacob,Blog,Python"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ["copy-to-clipboard.css"]
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ["copy-to-clipboard.js"]
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "花教授"
  name = "花教授"
  url = "http://www.profhua.com/"
[[params.links]]
  title = "强哥"
  name = "强哥"
  url = "https://me.csdn.net/julystroy"
[[params.links]]
  title = "吴松"
  name = "吴松"
  url = "http://blog.busyboy.cn"
[[params.links]]
  title = "我的博客园"
  name = "我的博客园"
  url = "http://www.cnblogs.com/breakering/"
[[params.links]]
  title = "金角大王"
  name = "金角大王"
  url = "https://www.cnblogs.com/alex3714/"
[[params.links]]
  title = "银角大王"
  name = "银角大王"
  url = "https://www.cnblogs.com/wupeiqi/"
[[params.links]]
  title = "导师刘又源"
  name = "导师刘又源"
  url = "https://www.cnblogs.com/zingp/"
[[params.links]]
  title = "赵凡"
  name = "赵凡"
  url = "https://www.cnblogs.com/zhaof/"

## 侧边栏广告位
[[params.ads]]
  title = "Give $100, Get $25"
  url = "https://www.vultr.com/?ref=8682518-6G"
  img = "https://www.vultr.com/media/banners/banner_800x418.png"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
    enable = true
    repo = "breakering/breakering.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  # 表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "monokai"

## 配置网站菜单
[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3
